### ISSUE TITLE
Live Update doesn't seem to update to the most recent error

### ISSUE THREAD

**Issue by D-Programming-Man** [D-Programming-Man/Pseudo#11]
When using the live update feature, it will only output errors from the previous state of the input text box.
For example: If we have something like this:
```
Create 
```
The line of the pseudo code will display it as:
```
Line ##: Create
```  
But when you update that line with this:
```
Create a
```
The same error message will appear:
```
Line ##: Create
```  
But if we update it again with this line:
```
Create a variable
```
It would now display this error line:
```
Line ##: Create a
```  
This is the previous error message we should've gotten from the past input box state. I'm thinking that it has something to do with the changed state of the input box when the threading.Timer thread joins back to the main thread. I'll have to keep out for this.

**Comment by dbarU** [comment]
The issue comes from line #125 in interpret.py where we return out of the while loop on errors, causing the the function to return from interpret rather than just the loop. Changes this to break actually also solves the execute issue, and if you add the clearing functions I added earlier today in the interpreter function in application.py it will clear the console/output so  it will look even nicer in my opinion.
I will add this change now
